# Generated by Django 5.1 on 2024-09-06 04:31

import django.db.models.deletion
import libs.truncate_table_mixin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата платежа')),
                ('amount', models.PositiveIntegerField(verbose_name='стоимость')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id платежной сессии')),
                ('link', models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на страницу платежа')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms.course', verbose_name='курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms.lesson', verbose_name='урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
                'ordering': ('user', 'course', 'lesson', 'amount'),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
    ]
