# Generated by Django 5.1 on 2024-08-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_course_options_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/lessons', verbose_name='превью изображение'),
        ),
    ]
