# Generated by Django 5.1 on 2024-09-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_rename_first_sending_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обновления'),
        ),
    ]
