# Generated by Django 5.1 on 2024-09-03 11:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_usersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user', 'course')},
        ),
    ]
